--LSOT 생성
CREATE USER LSOT IDENTIFIED BY 1111;
GRANT CONNECT, RESOURCE TO LSOT;
GRANT CREATE VIEW, CREATE SYNONYM TO LSOT;



------------------------MEMBER TABLE
DROP TABLE MEMBERS;
CREATE TABLE MEMBERS
(
    m_id             NVARCHAR2(20)    NOT NULL, 
    m_pw             NVARCHAR2(20)    NOT NULL, 
    m_name           NVARCHAR2(20)    NOT NULL, 
    m_phone          NVARCHAR2(13)    NOT NULL, 
    m_email          NVARCHAR2(30)    NOT NULL, 
    m_loc            NVARCHAR2(30)    NOT NULL, 
    m_gender         NVARCHAR2(5)     NOT NULL, 
    m_birth          NVARCHAR2(8)        NOT NULL, 
    m_pw_question    NVARCHAR2(20)    NOT NULL, 
    m_pw_answer      NVARCHAR2(20)    NOT NULL, 
    m_office_name    NVARCHAR2(20)    , 
    m_office_tel     NVARCHAR2(13)    , 
    m_kind           NVARCHAR2(2)     NOT NULL,   --개인,단체
    m_point          NUMBER           NOT NULL,
    M_BLACKLIST      NUMBER           DEFAULT '0',  --0이면 일반회원, 1이면 블랙리스트
    CONSTRAINT MEMBER_PK PRIMARY KEY (m_id)
);
CREATE SEQUENCE M_SEQ;
 alter table members modify(M_LOC nvarchar2(100));

INSERT INTO MEMBERS
VALUES('FFF','FFF','임수신','01055555555','임수신@NAVER.COM','인천 학익동','남자','19980101','옆자리 사람은?','배미정',
'수신스쿨','0325555555','단체','6000',1);

-----------------------------GIVE TABLE
DROP TABLE GIVE;
CREATE TABLE Give
(
    g_code        NVARCHAR2(5)     NOT NULL, 
    g_Mid         NVARCHAR2(20)    NOT NULL, 
    g_title       NVARCHAR2(20)    NOT NULL, 
    g_bigtalent   NVARCHAR2(100)   NOT NULL,
    g_smalltalent NVARCHAR2(100)   NOT NULL,
    g_loc         NVARCHAR2(20)    NOT NULL, 
    g_period_S    NVARCHAR2(20)    NOT NULL,
    g_period_E    NVARCHAR2(20)    NOT NULL,
    G_DATE        DATE             DEFAULT SYSDATE,
    g_hits        number,
    CONSTRAINT GIVE_PK PRIMARY KEY (g_code)
);
ALTER TABLE give
ADD(g_content NVARCHAR2(100));
ALTER TABLE Give
ADD CONSTRAINT FK_g_Mid FOREIGN KEY (g_Mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;

CREATE SEQUENCE G_SEQ;

select*from members;
INSERT INTO GIVE
VALUES('G'||G_SEQ.NEXTVAL,'AAA','기부해요','어학','한국어','인천 계양구','2017-06-20','2017-06-27',DEFAULT,0);
INSERT INTO GIVE
VALUES('G'||G_SEQ.NEXTVAL,'BBB','기부하고싶어요','컴퓨터','JAVA','인천 가좌동','2017-06-18','2017-06-30',DEFAULT,0);
INSERT INTO GIVE
VALUES('G'||G_SEQ.NEXTVAL,'DDD','기부','취미','요리','인천 학익동','2017-06-22','2017-06-25',DEFAULT,0);

-------------------------TAKE TABLE
DROP TABLE TAKE;
CREATE TABLE Take
(
    t_code              NVARCHAR2(5)     NOT NULL, 
    t_mid               NVARCHAR2(20)    NOT NULL, 
    t_kind              NVARCHAR2(2)     NOT NULL,  --개인,단체
    t_title             NVARCHAR2(20)    NOT NULL, 
    t_content           NVARCHAR2(100)   NOT NULL, 
    t_request_period_S  NVARCHAR2(20)    NOT NULL, 
    t_request_period_E  NVARCHAR2(20)    NOT NULL,
    t_service_period    NVARCHAR2(20)    NOT NULL, 
    t_gender            NVARCHAR2(5)     NOT NULL, 
    t_age               NVARCHAR2(20)    NOT NULL, 
    t_personnel         NVARCHAR2(20)    NOT NULL, 
    t_etc               NVARCHAR2(50)    , 
    t_filename          NVARCHAR2(50)    , 
    t_date              DATE             DEFAULT SYSDATE, 
    t_hits              number,
    CONSTRAINT TAKE_PK PRIMARY KEY (t_code)
);
alter table take modify(t_gender nvarchar2(5));
ALTER TABLE Take 
ADD CONSTRAINT FK_t_mid FOREIGN KEY (t_mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;

CREATE SEQUENCE T_SEQ;

insert into take
values('T'||T_SEQ.NEXTVAL,'AAA','단체','기부받고싶어요','JAVA배우고싶어요','2017-06-19','2017-06-29','2017-06-30','여자','20대',
'1명','미정스쿨 이수하신분 원해요','',DEFAULT,0);

-----------------------REVIEW TABLE
DROP TABLE REVIEW;
CREATE TABLE Review
(
    r_code        NVARCHAR2(5)     NOT NULL, 
    r_mid         NVARCHAR2(20)    NOT NULL, 
    r_title       NVARCHAR2(20)    NOT NULL, 
    r_name        NVARCHAR2(20)    NOT NULL, 
    r_when        NVARCHAR2(20)    NOT NULL, 
    r_content     NVARCHAR2(50)    NOT NULL, 
    r_place       NVARCHAR2(20)    NOT NULL, 
    r_feeling     NVARCHAR2(100)   NOT NULL, 
    r_filename1   NVARCHAR2(20)   ,
    r_filename2   NVARCHAR2(20)   ,
    r_filename3   NVARCHAR2(20)   ,
    R_DATE        DATE             DEFAULT SYSDATE,
    r_hits        number,
    CONSTRAINT REVIEW_PK PRIMARY KEY (r_code)
);

INSERT INTO REVIEW
VALUES('R'||R_SEQ.NEXTVAL,'AAA','후기 남겨요!!','허예림','2017-06-30','봉사 너~무 재밌다!','ICIA','봉사 더 많이 해야지','','','',DEFAULT,0);
INSERT INTO REVIEW
VALUES('R'||R_SEQ.NEXTVAL,'BBB','후기 여기있다!','배미정','2017-05-29','봉사 꿀잼','우체국','봉사 그만하고 싶다','','','',DEFAULT,0);
ALTER TABLE Review
ADD CONSTRAINT FK_r_mid FOREIGN KEY (r_mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;

CREATE SEQUENCE R_SEQ;

---------------------------------COMMENT TABLE
DROP TABLE COMMENTS;
CREATE TABLE Comments
(
    c_code       NVARCHAR2(5)     NOT NULL, 
    c_mid        NVARCHAR2(20)    NOT NULL,  
    c_date       DATE             DEFAULT SYSDATE, 
    c_content    NVARCHAR2(100)   NOT NULL, 
    c_gcode      NVARCHAR2(20)    ,   --기부하기0,기부받기(개인)1,기부받기(단체)2,후기3
    c_tcode      NVARCHAR2(20)    ,
    c_rcode      NVARCHAR2(20)    ,
    
    CONSTRAINT COMMENT_PK PRIMARY KEY (c_code)
);

ALTER TABLE Comments
ADD CONSTRAINT FK_c_mid FOREIGN KEY (c_mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;
ALTER TABLE comments
ADD CONSTRAINT FK_c_gcode FOREIGN KEY (c_gcode)
REFERENCES give (g_code) ON DELETE CASCADE;
ALTER TABLE comments
ADD CONSTRAINT FK_c_tcode FOREIGN KEY (c_tcode)
REFERENCES take (t_code) ON DELETE CASCADE;
ALTER TABLE comments
ADD CONSTRAINT FK_c_rcode FOREIGN KEY (c_rcode)
REFERENCES review (r_code) ON DELETE CASCADE;
ALTER TABLE Comments
ADD (RSTAR NUMBER DEFAULT 0);

CREATE SEQUENCE C_SEQ;

insert into comments
values('C'||C_SEQ.NEXTVAL,'AAA',DEFAULT,'ㅇㅇㅇㅇㅇㅇ','G3');

-----------------------------NOTICE TABLE
DROP TABLE NOTICE;
CREATE TABLE Notice
(
    n_code       NVARCHAR2(5)    NOT NULL, 
    n_title      NVARCHAR2(20)    NOT NULL, 
    n_content    NVARCHAR2(100)    NOT NULL, 
    N_DATE       DATE             DEFAULT SYSDATE,
    n_hits       number,
    CONSTRAINT NOTICE_PK PRIMARY KEY (n_code)
);

CREATE SEQUENCE N_SEQ;

INSERT INTO NOTICE
VALUES('N'||N_SEQ.NEXTVAL,'포인트 안내','기부하신 후 후기를 작성하시면 포인트 10추가',DEFAULT,0);
INSERT INTO NOTICE
VALUES('N'||N_SEQ.NEXTVAL,'포인트 후원안내','마이페이지에서 후원하기 누를시 총누적금액에 더해진후 매월 말 기부됩니다.',DEFAULT,0);


---------------------------REQUEST TABLE
DROP TABLE REQUEST;
CREATE TABLE Request
(
    q_code     NVARCHAR2(5)    NOT NULL, 
    q_mid      NVARCHAR2(20)   NOT NULL, 
    q_tcode    NVARCHAR2(20)   NOT NULL,
    Q_PROGRESS NUMBER          DEFAULT '0',  --0 : 수락요청, 1 : 수락완료, 2 : 수락거절, 3 : 봉사완료
    CONSTRAINT REQUEST_PK PRIMARY KEY (q_code)
);

ALTER TABLE Request
ADD CONSTRAINT FK_q_mid FOREIGN KEY (q_mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;

ALTER TABLE Request
ADD CONSTRAINT FK_q_tcode FOREIGN KEY (q_tcode)
REFERENCES Take (t_code) ON DELETE CASCADE;
INSERT INTO REQUEST
VALUES('Q'||Q_SEQ.NEXTVAL,'AAA','T41',0);
INSERT INTO REQUEST
VALUES('Q'||Q_SEQ.NEXTVAL,'AAA','T42',0);
        
CREATE SEQUENCE Q_SEQ;
        
---------------------------SUPPORT TABLE
DROP TABLE SUPPORT;
CREATE TABLE Support
(
    s_code     NVARCHAR2(5)    NOT NULL, 
    s_mid      NVARCHAR2(20)   NOT NULL, 
    s_total    NUMBER          NOT NULL, 
    S_DATE     DATE            DEFAULT SYSDATE,
    CONSTRAINT SUPPORT_PK PRIMARY KEY (s_code)
);

ALTER TABLE Support
ADD CONSTRAINT FK_s_mid FOREIGN KEY (s_mid)
REFERENCES MemberS (m_id) ON DELETE CASCADE;

CREATE SEQUENCE S_SEQ;

INSERT INTO SUPPORT
VALUES('S'||S_SEQ.NEXTVAL,'AAA',1500,DEFAULT);

-----------------------------BIGCLASS
DROP TABLE BIGCLASS;
CREATE TABLE BIGCLASS
( 
  BC_CODE NVARCHAR2(6),
  BC_KIND NVARCHAR2(20),
  CONSTRAINT BIGCLASS_PK PRIMARY KEY(BC_CODE)
);

INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'예술');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'취미');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'건축');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'교육');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'어학');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'전문분야');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'후원');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'사무행정');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'의료');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'영상');
INSERT INTO BIGCLASS
VALUES('BC'||BC_SEQ.NEXTVAL,'컴퓨터');

CREATE SEQUENCE BC_SEQ;


--------------------------SMALLCLASS
DROP TABLE SMALLCLASS;
CREATE TABLE SMALLCLASS
( 
  SC_CODE NVARCHAR2(6),
  SC_BCCODE NVARCHAR2(5),
  SC_KIND NVARCHAR2(20),
  CONSTRAINT SMALLCLASS_PK PRIMARY KEY(SC_CODE)
);

ALTER TABLE SMALLCLASS
ADD CONSTRAINT FK_SC_BCCODE FOREIGN KEY (SC_BCCODE)
REFERENCES BIGCLASS (BC_CODE);

INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC1','음악');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC1','미술');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC1','무용');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','요리');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','악기');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','스포츠');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','무용');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','사진');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','문예');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','원예');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC2','공예');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC3','설비');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC3','목공');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC3','도배');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC3','미장');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC3','인테리어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC4','컨설던트');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC4','심리치료');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC4','미술치료');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC4','음악치료');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','한국어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','중국어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','영어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','일본어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','한자');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC5','기타외국어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC6','법률');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC6','노무');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC6','세무');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC6','회계');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC8','문서기록');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC8','편집');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','한의학');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','양의학');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','약학');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','수의학');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','치위생');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC9','간호사');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC10','영상촬영');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC10','영상편집');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC11','C언어');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC11','C++');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC11','JAVA');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC11','FRONT');
INSERT INTO SMALLCLASS
VALUES('SC'||SC_SEQ.NEXTVAL,'BC11','홈페이지제작');



CREATE SEQUENCE SC_SEQ;


-------------------------------------------------------
SELECT * FROM MEMBERS WHERE M_BLACKLIST=0;
SELECT * FROM MEMBERS M INNER JOIN GIVE G
ON M_ID=G_MID
WHERE G_CODE='G5';
UPDATE REQUEST SET Q_PROGRESS=1 WHERE Q_CODE='Q2';
SELECT * FROM MEMBERS M INNER JOIN TAKE G ON M_ID=T_MID WHERE T_CODE='T41';
SELECT * FROM NOTICE WHERE N_CODE='N1';
DELETE FROM MEMBERS WHERE M_ID='CCC';
DELETE FROM COMMENTS WHERE C_CODE='C19';
select * from members where m_id='AAA' and m_pw='111';
SELECT * FROM REQUEST Q INNER JOIN TAKE T ON Q.Q_TCODE=T.T_CODE WHERE q_mID='AAA';
SELECT * FROM MEMBERS M INNER JOIN TAKE T ON M.M_ID=T.T_MID WHERE T_CODE='T41';
SELECT * FROM GIVE WHERE G_MID='AAA';
delete from support;

delete from review where r_code='R41';
---------------------------------------------------SELECT
SELECT * FROM MEMBERS;
SELECT * FROM GIVE;
SELECT * FROM TAKE;
SELECT * FROM REVIEW;
SELECT * FROM COMMENTS;
SELECT * FROM NOTICE;
SELECT * FROM REQUEST;
SELECT * FROM SUPPORT;
SELECT * FROM BIGCLASS;
SELECT * FROM SMALLCLASS;
SELECT * FROM USER_CONSTRAINTS;
---------------------------------------------------SELECT
delete from take where t_mid='DDD';
COMMIT;